//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUIZ_ATM.bussiness
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intrebari
    {
        public Intrebari()
        {
            this.Raspunsuris = new HashSet<Raspunsuri>();
        }
    
        public decimal id_intrebare { get; set; }
        public string text { get; set; }
        public decimal varianta_corecta { get; set; }
        public decimal id { get; set; }
    
        public virtual ICollection<Raspunsuri> Raspunsuris { get; set; }
    }
}
