//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUIZ_ATM.bussiness
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistica
    {
        public Nullable<decimal> id_utilizator { get; set; }
        public Nullable<decimal> Medie { get; set; }
        public Nullable<decimal> Nr_teste_parcurse { get; set; }
        public Nullable<decimal> Punctaj { get; set; }
        public decimal id { get; set; }
    
        public virtual Utilizatori Utilizatori { get; set; }
    }
}
