//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUIZ_ATM.bussiness
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilizatori
    {
        public Utilizatori()
        {
            this.Statisticas = new HashSet<Statistica>();
        }
    
        public decimal id_utilizator { get; set; }
        public string Nume { get; set; }
        public string Prenume { get; set; }
        public string Mail { get; set; }
        public string Parola { get; set; }
        public Nullable<decimal> Pozitie { get; set; }
    
        public virtual ICollection<Statistica> Statisticas { get; set; }
    }
}
